In [33]:
N = 10000
d = 2
Sample = rand(d,N);
k = 20

20

In [35]:
function kNN1(Sample::Array{Float64,2}, k::Int)
    Dist = zeros(N,N)
    for i=1:N
        for j=i+1:N
            Dist[i,j] = sum((Sample[:,i]-Sample[:,j]).^2)
            Dist[j,i] = Dist[i,j]
        end
    end
    Dist
    kNN_Dict = Dict(i=>Array{Int}(sortslices([Dist[i,:] collect(1:N)], dims = 1)[2:k+1,2]) for i=1:N)
end

kNN1 (generic function with 1 method)

In [34]:
kNN1(Sample, 5)

Dict{Int64,Array{Int64,1}} with 10000 entries:
  9775 => [932, 5626, 7986, 1852, 4429]
  2843 => [4827, 2613, 7871, 2364, 6062]
  4495 => [1120, 5573, 8598, 8504, 1899]
  6928 => [2251, 7454, 982, 9299, 8746]
  9905 => [3280, 5571, 4379, 2075, 9204]
  6380 => [1297, 9086, 4934, 2606, 7983]
  1316 => [9027, 2381, 2630, 1236, 8318]
  6265 => [7828, 4511, 6162, 1409, 7598]
  5459 => [1748, 2750, 9911, 5616, 6381]
  5842 => [5087, 7133, 9083, 7352, 6752]
  4473 => [5148, 3214, 2464, 884, 8213]
  5099 => [7305, 4355, 933, 2284, 2204]
  8312 => [2245, 8555, 5716, 6621, 3062]
  4460 => [7940, 9604, 9607, 8875, 2163]
  8805 => [6142, 1689, 8326, 681, 888]
  1333 => [7916, 4259, 5711, 6655, 1569]
  9934 => [4116, 6909, 8814, 6154, 4619]
  4517 => [8317, 5076, 7228, 2476, 2767]
  3485 => [4011, 6760, 2185, 5171, 4752]
  3120 => [5305, 17, 9081, 6108, 3054]
  1671 => [7256, 9728, 3904, 2681, 3784]
  1131 => [6093, 5466, 8382, 4673, 9230]
  5335 => [8765, 2098, 1638, 4207, 3809]
  6757 => [3368, 9

In [56]:
Pts_Orders = zeros(Int, size(Sample))
d = size(Sample, 1)
N = size(Sample, 2)
for i = 1:2
    Pts_Seq = sortslices([Sample[i,:] collect(1:N)], dims = 1)
    Orders = Array{Int,1}(sortslices([Pts_Seq[:,2] collect(1:N)], dims = 1)[:,2])
    Pts_Orders[i,:] = Orders
end
Pts_Orders

2×10000 Array{Int64,2}:
 2649  8094  8165  4936  8728  931  …  6271  2762  7179  3599  1392  7651
 9342  4308  8216    90  7888   64     8854  9925  4160  8734  8672  5976

In [60]:
GraphRep = zeros(Int, N,N)
for j=1:N
    GraphRep[Pts_Orders[:,j][1], Pts_Orders[:,j][2]] = j
end
GraphRep

10000×10000 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0 

In [13]:
using Clustering

In [20]:
n = 5
R = kmeans(Sample, n);

In [25]:
A = assignments(R)
C = counts(R);

In [27]:
using Plots
plotly()
Dict_Cluster = Dict(i=>Int[] for i=1:n)
scatter(Sample[1,:], Sample[2,:], label = "Sample")
for i=1:n
    Cluster_i = findall(A.==i)
    Dict_Cluster[i] = Cluster_i
    scatter!(Sample[1, Cluster_i], Sample[2, Cluster_i], label = "Cluster $i")
end
scatter!()

In [32]:
X1 = Sample[:,Dict_Cluster[2]]
X2 = Sample[:,Dict_Cluster[4]]

2×182 Array{Float64,2}:
 0.876368  0.76687   0.941793  0.723795  …  0.639369  0.497582  0.621907
 0.917419  0.620668  0.769491  0.876275     0.76793   0.814324  0.927618